environment:
  cvp:
    url: https://ui.cvp.core.umetrics.io
    eTitle: Umetrics Studio - Sartorius
    login: dariusz.hryciuk@sartorius.com
    password: Wazka1111!
    accountName: Dariusz Hryciuk
    active: false
  prod:
    url: https://ui.umetrics.studio
    eTitle: Umetrics Studio - Sartorius
    login: dariusz.hryciuk@sartorius.com
    password: Wazka1111!
    accountName: Dariusz Hryciuk
    active: false
  stag:
    url: https://staging.umetrics.studio/
    eTitle: Umetrics Studio - Sartorius
    login: dariusz.hryciuk@sartorius.com
    password: Wazka1111!
    accountName: Dariusz Hryciuk
    active: true

browser:
  headless: false           # false, true
  slomo: 500                # 2000
  channel: chrome           #chrome, firefox, webkit
  trace: true              # false, true