trigger:
  branches:
    include:
      - '*'

resources:
  repositories:
    - repository: templates
      type: git
      name: Umetrics/build-templates
      ref: refs/heads/master
      
jobs:
  - job: First_test
    pool:
      name: Default
      demands: sh

    steps:
      - template: steps/in-agent.yaml@templates
        parameters:
          command: |
            printf "Current environment"
            /usr/bin/java --version
            mvn -v
            update-java-alternatives --jre-headless --set java-1.11.0-openjdk-amd64
            JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
            printf "Updated alternatives"
            /usr/bin/java --version
            mvn -v
            mvn -f pom.xml clean test
          condition: succeededOrFailed()
          displayName: Run tests